### ISSUE TITLE
Wrong sklearn version

### ISSUE THREAD

**Issue by choosehappy** [sidhomj/DeepTCR#17]
requirements.txt states 0.19.1

but OneHotEncoder in that version doesn't have a "categories" named variable:

https://scikit-learn.org/0.19/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder

which is used here:

https://github.com/sidhomj/DeepTCR/blob/eb58a950939ce26b57f710994fc3e1cac35b3496/DeepTCR/DeepTCR.py#L324

This wasn't introduced until version 0.20

**Comment by sidhomj** [comment]
thank you for letting me know! will update the requirements soon!
