### ISSUE TITLE
Error while running 6 - KNN classification tutorial

### ISSUE THREAD

**Issue by choosehappy** [sidhomj/DeepTCR#19]
similar to #18 , but in a different file:

![image](https://user-images.githubusercontent.com/9681868/68876302-86bcb880-0704-11ea-9b38-b521cfe84a34.png)

All the other tutorials work : )

**Comment by sidhomj** [comment]
I can't replicate this error.. can you try running the tutorial again?

**Comment by sidhomj** [comment]
also thank you for your help in making sure the package works?

**Comment by choosehappy** [comment]
i think this one is on me, i tried to reproduce but can't.

i realize now it was running a cached version in a separate jupyter notebook, and your last commit actually resolves. thanks!
