### ISSUE TITLE
Add Pillow to requirements

### ISSUE THREAD

**Issue by choosehappy** [sidhomj/DeepTCR#21]
Otherwise one receives an error saying TIF not supported when making heatmaps:

![image](https://user-images.githubusercontent.com/9681868/68990417-035dad00-0853-11ea-9bf5-df208448ecaf.png)

**Comment by sidhomj** [comment]
you mean add pillow as an import?

**Comment by choosehappy** [comment]
in the requirements.txt should do it?

i didn't modify your code, but received that error
then did a "pip install pillow"
then reran the same code and the error disappeared

i suspect it may be an "optional" dependency for the other libraries so
isn't it automatically installed when doing pip install -r requirements.txt

**Comment by sidhomj** [comment]
got it

**Comment by sidhomj** [comment]
updated requirements.txt file. Now when you install, pip should also install all dependencies as well except for PhenoGraph which needs to be installed separately.

**Comment by choosehappy** [comment]
actually, you can add:

git+https://github.com/jacoblevine/phenograph.git

to the requirements.txt list and it will install it as well

btw, currently on line 19:

https://github.com/sidhomj/DeepTCR/blob/becc96bf709fdbac6cf8a634a33e21aedf32839d/requirements.txt#L19

there is an effort to load phenograph, which ends up causing an error:

```
  Could not find a version that satisfies the requirement PhenoGraph==1.5.2 (from -r requirements.txt (line 19)) (from versions: )
No matching distribution found for PhenoGraph==1.5.2 (from -r requirements.txt (line 19))
```

**Comment by sidhomj** [comment]
so it turns out when running the setup.py file, it can only install packages on pypi. I'm having difficulty getting the setup.py file to install phenograph with that command in the requirements.txt file
