### ISSUE TITLE
VAE AUC violin plot Y-axis value >1

### ISSUE THREAD

**Issue by hejing3283** [sidhomj/DeepTCR#3]
I am running the unsupervised tutorial by 

# Instantiate training object
DTCRU = DeepTCR_U('Tutorial')

#Load Data from directories
DTCRU.Get_Data(directory='github/DeepTCR/Data/Rudqvist',Load_Prev_Data=False,aggregate_by_aa=True,
               aa_column_beta=1,count_column=2,v_beta_column=7,d_beta_column=14,j_beta_column=21)

#Train VAE
DTCRU.Train_VAE(Load_Prev_Data=False,accuracy_min=0.9)

#### Output-----------
Finding 30 nearest neighbors using minkowski metric and 'auto' algorithm
Neighbors computed in 50.87618613243103 seconds
Jaccard graph constructed in 12.015304803848267 seconds
Wrote graph to binary file in 3.909883975982666 seconds
Running Louvain modularity optimization
After 1 runs, maximum modularity is Q = 0.991586
Louvain completed 21 runs in 9.033319234848022 seconds
PhenoGraph complete in 75.99179887771606 seconds
Clustering Done
![AUC__1](https://user-images.githubusercontent.com/2622497/56503594-e5f67980-64e3-11e9-9ba0-d9b95014bdae.png)

**Comment by sidhomj** [comment]
violin plots model the distribution of the underlying data. The actual points are not greater than 1. You can change the plot type to a different one like boxplot or swarm plot.

**Comment by hejing3283** [comment]
In this case I think violin plot is not a good choice for visualization. Thanks a lot!

**Comment by sidhomj** [comment]
In that case, change the plot_type parameter:

        plot_type: str
            Type of plot as taken by seaborn.catplot for kind parameter:
            options include (strip,swarm,box,violin,boxen,point,bar,count)
