### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by sinnamone** [sidhomj/DeepTCR#33]
Hi sidhomj,

very nice tool, i have doubt, it can be used with SMART-Seq v4 PLUS Kit or SMARTer Human TCR ab Profiling kit ?

Simone

**Comment by sidhomj** [comment]
As long as you can format your data in one of two formats, it can be uploaded into DeepTCR. See the following tutorial:

https://github.com/sidhomj/DeepTCR/blob/master/tutorials/1%20-%20Loading%20Data%20(Introduction).ipynb
