### ISSUE TITLE
Error when changing max_length

### ISSUE THREAD

**Issue by emm1R** [sidhomj/DeepTCR#34]
Hi,
In Train_VAE(), a ValueError is raised if a different max_length has been given to DeepTRC_U. The tensor shapes do not match on row 2292 when tf.equal() is called.

![Näyttökuva 2020-12-5 kello 2 48 19](https://user-images.githubusercontent.com/20052903/101228471-7f1bd900-36a4-11eb-95e5-8fdcd1474278.png)

**Comment by sidhomj** [comment]
Just to confirm, you're trying to use a max length of 70 for your analysis?

**Comment by sidhomj** [comment]
Updated the code to fix this issue. should be able now to use any max_length argument with the VAE. Let me know if this solves the problem! Thanks for using DeepTCR!

**Comment by emm1R** [comment]
Yes, it works now. Thank you!
And yes, I am using a max_length of 70. There were a very small percentage of TCRs that were longer than 40 and I didn’t want them to be filtered out. Will this impact the training or clustering in any negative way?

**Comment by sidhomj** [comment]
It shouldn't! Just wanted to make sure I was solving for the right use-case. It's actually a feature I was meaning to write but I had not gotten around to handing other input lengths for the VAE. The max_length argument was put in initially for the supervised models but I had to write a bit of code of modify VAE for other length inputs (other than 40). Thank you for highlighting this!
