### ISSUE TITLE
Sequence not featurized

### ISSUE THREAD

**Issue by fbenedett** [sidhomj/DeepTCR#51]
Dear all,

I am trying to analyze a dataset but, for unknown reasons, some of the sequences are not considered.

My code is the follow

```
%%capture
import sys
import pandas as pd
sys.path.append('../../')
from DeepTCR.DeepTCR import DeepTCR_U

# Instantiate training object
DTCRU = DeepTCR_U('Tutorial')

a_target="MA0"
#Load Data from directories
DTCRU.Get_Data(directory='data_deep_tcr/'+a_target,Load_Prev_Data=False,aggregate_by_aa=True,
               aa_column_beta=0,count_column=1,v_beta_column=2,j_beta_column=3)

#Train VAE
DTCRU.Train_VAE(Load_Prev_Data=False, size_of_net="small")
DTCRU.Cluster(clustering_method='phenograph', sample=500)
DFs = DTCRU.Cluster_DFs

r_df=pd.DataFrame()

for i in range(0, len(DFs)):
    tdf=DFs[i]
    tdf["cluster_index"]=i
    r_df=r_df.append(tdf)

fn="result_clustering_MA0_clean.txt" 
r_df.to_csv(fn)

```

In the directory "data_deep_tcr/MA0 I have two subfolders.  Each of these subfolders contains one TSV file with the following format:
```
aminoAcid	counts	v_beta	j_beta
CASTHLDPPGEQYFG	571795	hTRBV28	hTRBJ02-7
CASSPLGASGEQFFG	317906	hTRBV28	hTRBJ02-1
CASGGGEQFFG	104692	hTRBV12-3	hTRBJ02-1
CANEGASENTEAFFG	86447	hTRBV06-1	hTRBJ01-1
CASSFFPFNEQFFG	74908	hTRBV12-3	hTRBJ02-1

```

For example, I pass this sequence (with the v_beta and j_beta and the counts)
CANEGASENTEAFFG 73703 hTRBV06-8 hTRBJ01-1
but it is not clustered.

Whereas, the same sequence with a different count, v_beta and j_beta is clustered:
CANEGASENTEAFFG 86447 hTRBV06-1 hTRBJ01-17

Any idea why is this happening?

**Comment by fbenedett** [comment]
Please, reopen the issue.  The fact that the same sequence with different v_beta j_beta is not featurize is still a problem.

**Comment by sidhomj** [comment]
I think I know what your issue is. If you pass the parameter (aggregate_by_aa = True), DeepTCR collapses all TCR's with the same amino acid sequence. In this case, the only one of the v/d/j labels is taken in this collapse. Try setting the parameter to aggregate_by_aa = False and it should keep both those sequences separate in the featurization. Let me know if this works.

**Comment by fbenedett** [comment]
Thank you. That was the problem.
