### ISSUE TITLE
Extract accuracy of decoded TCRs from Sequence_inference

### ISSUE THREAD

**Issue by JulianSpagnuolo** [sidhomj/DeepTCR#56]
I'd like to get the encoding accuracy of TCRs encoded on a VAE model trained on an initial dataset. i.e. How could I extract the encoding accuracy as well as the latent encoded variables from DTCRU.Sequence_Inference()?

**Comment by sidhomj** [comment]
The way the method is written write now, there is no way to extract the accuracy during inference. This is something I will put as something to consider adding in a future release. As for getting the latent variables, the output of the method returns the latent encodings.
