### ISSUE TITLE
Getting an import error when running 'from DeepTCR.DeepTCR import DeepTCR_U'

### ISSUE THREAD

**Issue by dsrai** [sidhomj/DeepTCR#59]
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by sidhomj** [comment]
make sure you are using the right version of biopython. biopython==1.76
