### ISSUE TITLE
Heatmap save to file output blank file

### ISSUE THREAD

**Issue by hejing3283** [sidhomj/DeepTCR#6]
DTCRU.HeatMap_Sequences(filename='Heatmap_Sequences.pdf')

The resulted file is blank.

**Comment by sidhomj** [comment]
The output must be an image. Not a pdf.

Sent from my iPhone

On Apr 26, 2019, at 11:50 AM, Jing He <notifications@github.com<mailto:notifications@github.com>> wrote:


DTCRU.HeatMap_Sequences(filename='Heatmap_Sequences.pdf')

The resulted file is blank.

**Comment by hejing3283** [comment]
so it's a png, the tiff is not supported?

**Comment by sidhomj** [comment]
It may depend on the OS you are using. I think tiff should work on Linux systems. I generally use either eps or png.

Sent from my iPhone

On Apr 26, 2019, at 12:05 PM, Jing He <notifications@github.com<mailto:notifications@github.com>> wrote:


so it's a png, the tiff is not supported?

**Comment by hejing3283** [comment]
I use macOS and linux. None of them works. Cannot save to eps or png neither.

**Comment by sidhomj** [comment]
Will look at this later tonight. Sorry for the delay.

Sent from my iPhone

On Apr 26, 2019, at 1:20 PM, Jing He <notifications@github.com<mailto:notifications@github.com>> wrote:


I use macOS and linux. None of them works. Cannot save to eps or png neither.

**Comment by hejing3283** [comment]
Thanks!

**Comment by sidhomj** [comment]
hmm. i'm not having a problem saving png or eps images.. are you getting an actual error?

**Comment by hejing3283** [comment]
No error at all. Just blank page.

**Comment by sidhomj** [comment]
with with png? I can't replicate the problem on my end so it's hard to know how to fix it.. can you try running DeepTCR within an IDE like pycharm? as oppose to just from cmd.

**Comment by hejing3283** [comment]
I tried .tif, png, off, eps, none of them works. But from Jupyter notebook, it shows up. 

Best,
Jing

**Comment by sidhomj** [comment]
So it’s only a problem when running DeepTCR from command line?


Sent from my iPhone

On Apr 27, 2019, at 11:15 AM, Jing He <notifications@github.com<mailto:notifications@github.com>> wrote:

I tried .tif, png, off, eps, none of them works. But from Jupyter notebook, it shows up.

Best,
Jing

**Comment by hejing3283** [comment]
The heatmap shows up in notebook, but cannot be saved to a file no matter how I run it. 

Best,
Jing

**Comment by hejing3283** [comment]
I installed pillow and set the backend as 'pdf'  by the following scripts, it works now. 

import matplotlib
matplotlib.use("pdf")
