### ISSUE TITLE
parallele for KNN 

### ISSUE THREAD

**Issue by hejing3283** [sidhomj/DeepTCR#7]
Could we add n_jobs to the KNN_Sequence_Classifier by adding n_jobs to KNeighborsClassifier from sklearn module? Currently the KNN_Sequence_Classifier is very slow. 

Thanks!

**Comment by sidhomj** [comment]
sure thing but if I remember correctly, when I've tried to use the KNeighborsClassifier in parallel, it weirdly ends up being slower but I can add it in in there.

**Comment by sidhomj** [comment]
Just pushed the updated to parallelize into the method to the master branch. Let me know if you if you have any problems with it!

**Comment by hejing3283** [comment]
Thanks! I will let you know after I finish running.
